#!/usr/bin/env python3
"""Generates Resources/burnrate-symbolic.svg from the same 72-unit geometry as
scripts/make_icon.swift, so the Linux menu-bar icon is the same "Dial Core"
mark the macOS status item draws.

macOS uses a *template* image (a monochrome silhouette the system recolours for
light/dark menu bars); the Linux equivalent is a symbolic icon, which panels
recolour from the theme. So this is the flame with the dial core punched out
and the needle left in the knocked-out hole, drawn in one colour.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Flame outline, verbatim from scripts/make_icon.swift (72-unit space, y-down).
FLAME = (
    "M 36 6 "
    "C 33 14 24 20 19.5 27 "
    "C 16.5 32 15.5 36.5 15.5 41 "
    "C 15.5 52 24.5 60 36 60 "
    "C 47.5 60 56.5 52 56.5 41 "
    "C 56.5 36.5 55.5 32 52.5 27 "
    "C 48 20 39 14 36 6 Z"
)
DIAL_CENTER = (36, 42)
DIAL_RADIUS = 10.5
PIVOT = (36, 46)
PIVOT_RADIUS = 2.2
NEEDLE_LENGTH = 22
NEEDLE_WIDTH = 2.6
REST_ANGLE_DEG = 18  # matches the macOS "rest pose" (70% remaining)

import math

radians = math.radians(REST_ANGLE_DEG)
tip = (PIVOT[0] + NEEDLE_LENGTH * math.sin(radians),
       PIVOT[1] - NEEDLE_LENGTH * math.cos(radians))


def dial_circle() -> str:
    cx, cy = DIAL_CENTER
    return (f"M {cx - DIAL_RADIUS} {cy} "
            f"A {DIAL_RADIUS} {DIAL_RADIUS} 0 1 0 {cx + DIAL_RADIUS} {cy} "
            f"A {DIAL_RADIUS} {DIAL_RADIUS} 0 1 0 {cx - DIAL_RADIUS} {cy} Z")


def pivot_circle() -> str:
    cx, cy = PIVOT
    r = PIVOT_RADIUS
    return (f"M {cx - r} {cy} "
            f"A {r} {r} 0 1 0 {cx + r} {cy} "
            f"A {r} {r} 0 1 0 {cx - r} {cy} Z")


svg = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/make_symbolic_icon.py - do not edit by hand.
     Geometry matches scripts/make_icon.swift so the Linux menu-bar icon is the
     same mark as the macOS status item. Single colour so the panel can
     recolour it, the way macOS recolours a template image. -->
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 72 72">
  <g fill="currentColor" stroke="none">
    <!-- Flame with the dial core knocked out (evenodd turns the circle into a
         hole, matching the macOS destinationOut punch). -->
    <path fill-rule="evenodd" d="{FLAME} {dial_circle()}"/>
    <!-- Needle + pivot sit inside the hole, so they read against it. -->
    <path d="M {PIVOT[0]} {PIVOT[1]} L {tip[0]:.3f} {tip[1]:.3f}"
          fill="none" stroke="currentColor" stroke-width="{NEEDLE_WIDTH}"
          stroke-linecap="round"/>
    <path d="{pivot_circle()}"/>
  </g>
</svg>
"""

target = ROOT / "Resources" / "burnrate-symbolic.svg"
target.write_text(svg, encoding="utf-8")
print(f"written: {target}")
